HOSTS:
  centos9-systemd:
    platform: el-9-x86_64
    ip: 127.0.0.1
    image: quay.io/centos/centos:stream9
    hypervisor: docker
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - dnf install -y cronie initscripts wget systemd iproute
CONFIG:
  log_level: verbose
  type: foss