HOSTS:
  debian12-systemd:
    platform: debian-12-x86_64
    ip: 127.0.0.1
    image: debian:12
    hypervisor: docker
    docker_cmd: '["/sbin/init", "--log-target=console", "--log-level=debug"]'
    docker_image_commands:
      - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y systemd systemd-sysv dbus dbus-daemon cron openssh-server iproute2 wget
CONFIG:
  log_level: verbose
  type: foss
