HOSTS:
  el9-systemd:
    platform: el-9-x86_64
    ip: 127.0.0.1
    image: rockylinux:9
    hypervisor: docker
    docker_cmd: '["/usr/sbin/init", "--log-target=console", "--log-level=debug"]'
    docker_image_commands:
      - dnf install -y cronie initscripts wget systemd iproute
CONFIG:
  log_level: verbose
  type: foss
