HOSTS:
  ubuntu24-systemd:
    platform: ubuntu-24.04-x86_64
    ip: 127.0.0.1
    image: ubuntu:24.04
    hypervisor: docker
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y systemd systemd-sysv cron openssh-server wget
    dockeropts:
      Privileged: true
      HostConfig:
        Tmpfs:
          /run: ''
          /run/lock: ''
        Binds:
          - /sys/fs/cgroup:/sys/fs/cgroup:rw
CONFIG:
  log_level: verbose
  type: foss