HOSTS:
  ubuntu24-systemd:
    platform: ubuntu-24.04-x86_64
    ip: 127.0.0.1
    image: ubuntu:24.04
    hypervisor: docker
    docker_cmd: '["/sbin/init"]'
    docker_image_commands:
      - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y systemd systemd-sysv dbus dbus-daemon cron openssh-server iproute2 wget
CONFIG:
  log_level: verbose
  type: foss